export const FETCH_POPULAR_COINS = 'FETCH_POPULAR_COINS';
export const FETCH_POPULAR_COINS_SUCCESS = 'FETCH_POPULAR_COINS_SUCCESS';
export const FETCH_POPULAR_COINS_FAILURE = 'FETCH_POPULAR_COINS_FAILURE';

export const FETCH_POPULAR_COINS_DETAILS = 'FETCH_POPULAR_COINS_DETAILS';
export const FETCH_POPULAR_COINS_DETAILS_SUCCESS =
  'FETCH_POPULAR_COINS_DETAILS_SUCCESS';
export const FETCH_POPULAR_COINS_DETAILS_FAILURE =
  'FETCH_POPULAR_COINS_DETAILS_FAILURE';

export const FETCH_TRENDING_COINS = 'FETCH_TRENDING_COINS';
export const FETCH_TRENDING_COINS_SUCCESS = 'FETCH_TRENDING_COINS_SUCCESS';
export const FETCH_TRENDING_COINS_FAILURE = 'FETCH_TRENDING_COINS_FAILURE ';

export const FETCH_TRENDING_COINS_DETAILS = 'FETCH_TRENDING_COINS_DETAILS';
export const FETCH_TRENDING_COINS_DETAILS_SUCCESS =
  'FETCH_TRENDING_COINS_DETAILS_SUCCESS';
export const FETCH_TRENDING_COINS_DETAILS_FAILURE =
  'FETCH_TRENDING_COINS_DETAILS_FAILURE';

export const FOLLOW_COIN = 'FOLLOW_COIN';
export const UNFOLLOW_COIN = 'UNFOLLOW_COIN';

export const FETCH_FOLLOWING_COINS_DETAILS = 'FETCH_FOLLOWING_COINS_DETAILS';
export const FETCH_FOLLOWING_COINS_DETAILS_SUCCESS =
  'FETCH_FOLLOWING_COINS_DETAILS_SUCCESS';
export const FETCH_FOLLOWING_COINS_DETAILS_FAILURE =
  'FETCH_FOLLOWING_COINS_DETAILS_FAILURE';

export const START_COIN_NOTIFICATION = 'START_COIN_NOTIFICATION';
export const STOP_COIN_NOTIFICATION = 'STOP_COIN_NOTIFICATION';

export const FETCH_TOTALCOINS = 'FETCH_ALLCOINS';
export const FETCH_TOTALCOINS_SUCCESS = 'FETCH_ALLCOINS_SUCCESS';
export const FETCH_TOTALCOINS_FAILURE = 'FETCH_ALLCOINS_FAILURE';
