export const FETCH_LATEST_LISTINGS = 'FETCH_LATEST_LISTINGS';
export const FETCH_LATEST_LISTINGS_SUCCESS = 'FETCH_LATEST_LISTINGS_SUCCESS';
export const FETCH_LATEST_LISTINGS_FAILURE = 'FETCH_LATEST_LISTINGS_FAILURE';

export const FETCH_COINS_INFO = 'FETCH_COINS_INFO';
export const FETCH_COINS_INFO_SUCCESS = 'FETCH_COINS_INFO_SUCCESS';
export const FETCH_COINS_INFO_FAILURE = 'FETCH_COINS_INFO_FAILURE';
